### ISSUE TITLE
Use file_systen inside escript

### ISSUE THREAD

**Issue by pmartinezalvarez** [falood/file_system#34] opened 2017-08-02 14:34 UTC
I am interested in using the library inside an escript. When I call `{:ok, watcher_pid} = FileSystem.start_link(args)` from `iex` evrithing is ok. But when I run the same code inside an escript it returns `:ignore`

Is there a way to deal with it?

Thanks.

**Comment by falood** [comment] 2017-08-02 15:54
Thank you for this reporter, I never try it in escript, will do and fix it
asap :heart:

**Comment by pmartinezalvarez** [comment] 2017-08-02 16:38
Thanks!

**Comment by falood** [comment] 2017-08-04 06:23
@pmartinezalvarez I check the code, the issue is because we can't use `:code.priv_dir` in escript, I'll think more about how to make it configurable and works with both escript and distillery.
Will do it this weekend.

**Comment by pmartinezalvarez** [comment] 2017-08-04 07:47
Thanks @falood :) I have been thinking in loading the `/mac_listener` at compilation time, on the `fs_mac.ex` file, as suggested in https://elixirforum.com/t/is-it-possible-to-include-resource-files-when-packaging-my-project-using-mix-escript/730/10.

**Comment by falood** [comment] 2017-08-06 19:40
I tried to compile c_src to binary for `fs_mac` at runtime if the executable file is not exists, but `escript` runtime don't have application `:file_system`, `Mix` and the `c_src` folder to compile.
So even though I added the way to config executable file path via `config.exs` or `FILESYSTEM_FSMAC_EXECUTABLE_FILE` env, the binary file should also be compiled manually with `FILESYSTEM_FSMAC_EXECUTABLE_FILE=YOUR_EXECUTABLE_FILE_PATH mix file_system.fs_mac init` before run `mix escript.build`.

It seems no better way to do everything automatic 😞

**Comment by pmartinezalvarez** [comment] 2017-08-08 07:03
Thanks so much @falood! This is good enough for my use case.

**Comment by falood** [comment] 2017-08-08 16:11
file_system 0.1.4 released with this fix, enjoy ❤️

**Closed as completed by falood** 2017-08-08 16:11 UTC
